on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install

      - name: Bump version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch -m "chore: bump version to v%s"

      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push
        run: git push origin --follow-tags
